var auction_items = [
    // {
    //     "item_number": 190,
    //     "item_name": "CHANEL衣服",
    //     "unit": "件",
    //     "quantity": 1,
    //     "price": "30,000",
    //     "item_description": "尺寸34",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 191,
    //     "item_name": "CHANEL衣服",
    //     "unit": "件",
    //     "quantity": 1,
    //     "price": "15,000",
    //     "item_description": "尺寸38",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 192,
    //     "item_name": "CHANEL衣服",
    //     "unit": "件",
    //     "quantity": 1,
    //     "price": "18,000",
    //     "item_description": "尺寸36",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 193,
    //     "item_name": "CHANEL衣服",
    //     "unit": "件",
    //     "quantity": 1,
    //     "price": "20,000",
    //     "item_description": "尺寸34",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 194,
    //     "item_name": "CHANEL衣服",
    //     "unit": "件",
    //     "quantity": 1,
    //     "price": "80,000",
    //     "item_description": "尺寸34",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 195,
    //     "item_name": "CHANEL衣服",
    //     "unit": "件",
    //     "quantity": 1,
    //     "price": "20,000",
    //     "item_description": "尺寸34",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 196,
    //     "item_name": "CHANEL衣服",
    //     "unit": "件",
    //     "quantity": 2,
    //     "price": "150,000",
    //     "item_description": "編號196、198   係一套, 尺寸均為36",
    //     "num_images": 2,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 197,
    //     "item_name": "CHANEL衣服",
    //     "unit": "件",
    //     "quantity": 1,
    //     "price": "20,000",
    //     "item_description": "尺寸36",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 199,
    //     "item_name": "CHANEL衣服",
    //     "unit": "件",
    //     "quantity": 1,
    //     "price": "20,000",
    //     "item_description": "尺寸36",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 200,
    //     "item_name": "CHANEL衣服",
    //     "unit": "件",
    //     "quantity": 1,
    //     "price": "15,000",
    //     "item_description": "尺寸34",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 201,
    //     "item_name": "CHANEL衣服",
    //     "unit": "件",
    //     "quantity": 1,
    //     "price": "150,000",
    //     "item_description": "尺寸36",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 202,
    //     "item_name": "CHANEL衣服",
    //     "unit": "件",
    //     "quantity": 1,
    //     "price": "60,000",
    //     "item_description": "尺寸34",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 203,
    //     "item_name": "CHANEL衣服",
    //     "unit": "件",
    //     "quantity": 1,
    //     "price": "18,000",
    //     "item_description": "尺寸36",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 204,
    //     "item_name": "CHANEL衣服",
    //     "unit": "件",
    //     "quantity": 1,
    //     "price": "100,000",
    //     "item_description": "尺寸36",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 205,
    //     "item_name": "CHANEL衣服",
    //     "unit": "件",
    //     "quantity": 1,
    //     "price": "160,000",
    //     "item_description": "尺寸34",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 206,
    //     "item_name": "CHANEL衣服",
    //     "unit": "件",
    //     "quantity": 1,
    //     "price": "80,000",
    //     "item_description": "尺寸36",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 207,
    //     "item_name": "CHANEL衣服",
    //     "unit": "件",
    //     "quantity": 1,
    //     "price": "100,000",
    //     "item_description": "尺寸34",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 208,
    //     "item_name": "CHANEL衣服",
    //     "unit": "件",
    //     "quantity": 1,
    //     "price": "80,000",
    //     "item_description": "尺寸38",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 209,
    //     "item_name": "CHANEL衣服",
    //     "unit": "件",
    //     "quantity": 1,
    //     "price": "30,000",
    //     "item_description": "尺寸38",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 269,
    //     "item_name": "HERMES手環手錶",
    //     "unit": "個",
    //     "quantity": 1,
    //     "price": "22,000",
    //     "item_description": "",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 271,
    //     "item_name": "CHANEL手環",
    //     "unit": "個",
    //     "quantity": 1,
    //     "price": "120,000",
    //     "item_description": "",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 272,
    //     "item_name": "HERMES手環",
    //     "unit": "個",
    //     "quantity": 1,
    //     "price": "35,000",
    //     "item_description": "",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 273,
    //     "item_name": "HERMES手環",
    //     "unit": "個",
    //     "quantity": 1,
    //     "price": "35,000",
    //     "item_description": "",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 274,
    //     "item_name": "CHANEL手環",
    //     "unit": "個",
    //     "quantity": 1,
    //     "price": "50,000",
    //     "item_description": "",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 275,
    //     "item_name": "HERMES手環",
    //     "unit": "個",
    //     "quantity": 1,
    //     "price": "35,000",
    //     "item_description": "",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 276,
    //     "item_name": "HERMES手環",
    //     "unit": "個",
    //     "quantity": 1,
    //     "price": "35,000",
    //     "item_description": "",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 277,
    //     "item_name": "ROGER VIVIER手環",
    //     "unit": "個",
    //     "quantity": 1,
    //     "price": "35,000",
    //     "item_description": "",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 278,
    //     "item_name": "ROGER VIVIER手環",
    //     "unit": "個",
    //     "quantity": 1,
    //     "price": "35,000",
    //     "item_description": "",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 279,
    //     "item_name": "CHANEL手環",
    //     "unit": "個",
    //     "quantity": 1,
    //     "price": "40,000",
    //     "item_description": "",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 280,
    //     "item_name": "CHANEL手環",
    //     "unit": "個",
    //     "quantity": 1,
    //     "price": "40,000",
    //     "item_description": "",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 281,
    //     "item_name": "CHANEL手環",
    //     "unit": "個",
    //     "quantity": 1,
    //     "price": "40,000",
    //     "item_description": "",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 282,
    //     "item_name": "CHANEL手環",
    //     "unit": "個",
    //     "quantity": 1,
    //     "price": "40,000",
    //     "item_description": "",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 283,
    //     "item_name": "CHANEL手環",
    //     "unit": "個",
    //     "quantity": 1,
    //     "price": "40,000",
    //     "item_description": "",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // },
    // {
    //     "item_number": 284,
    //     "item_name": "CHANEL手環",
    //     "unit": "個",
    //     "quantity": 1,
    //     "price": "40,000",
    //     "item_description": "",
    //     "num_images": 1,
    //     "num_videos": 0,
    //     "auction_type": "變賣"
    // }
];