var auction_items = [
  {
    "item_number": 210,
    "item_name": "CHANEL包",
    "unit": "個",
    "quantity": 1,
    "price": "8,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 211,
    "item_name": "CHANEL包",
    "unit": "個",
    "quantity": 1,
    "price": "60,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 212,
    "item_name": "CHANEL包",
    "unit": "個",
    "quantity": 1,
    "price": "100,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 213,
    "item_name": "CHANEL包",
    "unit": "個",
    "quantity": 1,
    "price": "100,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 214,
    "item_name": "CHANEL包",
    "unit": "個",
    "quantity": 1,
    "price": "100,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 215,
    "item_name": "CHANEL包",
    "unit": "個",
    "quantity": 1,
    "price": "120,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 216,
    "item_name": "CHANEL包",
    "unit": "個",
    "quantity": 1,
    "price": "5,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 217,
    "item_name": "CHANEL包",
    "unit": "個",
    "quantity": 1,
    "price": "10,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 218,
    "item_name": "CHANEL包",
    "unit": "個",
    "quantity": 1,
    "price": "12,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 219,
    "item_name": "CHANEL包",
    "unit": "個",
    "quantity": 1,
    "price": "5,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 220,
    "item_name": "CHANEL包",
    "unit": "個",
    "quantity": 1,
    "price": "8,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 221,
    "item_name": "CHANEL包",
    "unit": "個",
    "quantity": 1,
    "price": "6,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 222,
    "item_name": "CHANEL包",
    "unit": "個",
    "quantity": 1,
    "price": "20,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 223,
    "item_name": "CHANEL包",
    "unit": "個",
    "quantity": 1,
    "price": "4,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 224,
    "item_name": "CHANEL包",
    "unit": "個",
    "quantity": 1,
    "price": "35,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 225,
    "item_name": "CHANEL包",
    "unit": "個",
    "quantity": 1,
    "price": "20,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 226,
    "item_name": "CHANEL包",
    "unit": "個",
    "quantity": 1,
    "price": "18,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 227,
    "item_name": "CHANEL包",
    "unit": "個",
    "quantity": 1,
    "price": "50,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 228,
    "item_name": "CHANEL包",
    "unit": "個",
    "quantity": 1,
    "price": "15,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 229,
    "item_name": "CHANEL包",
    "unit": "個",
    "quantity": 1,
    "price": "12,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 230,
    "item_name": "CHANEL包",
    "unit": "個",
    "quantity": 1,
    "price": "90,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 231,
    "item_name": "CHANEL包",
    "unit": "個",
    "quantity": 1,
    "price": "20,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 232,
    "item_name": "HERMES包",
    "unit": "個",
    "quantity": 1,
    "price": "35,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 233,
    "item_name": "HERMES包",
    "unit": "個",
    "quantity": 1,
    "price": "70,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 234,
    "item_name": "HERMES包",
    "unit": "個",
    "quantity": 1,
    "price": "15,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 235,
    "item_name": "HERMES包",
    "unit": "個",
    "quantity": 1,
    "price": "10,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 236,
    "item_name": "HERMES包",
    "unit": "個",
    "quantity": 1,
    "price": "5,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 237,
    "item_name": "HERMES包",
    "unit": "個",
    "quantity": 1,
    "price": "20,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 238,
    "item_name": "HERMES包",
    "unit": "個",
    "quantity": 1,
    "price": "35,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 239,
    "item_name": "HERMES包",
    "unit": "個",
    "quantity": 1,
    "price": "35,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 240,
    "item_name": "HERMES包",
    "unit": "個",
    "quantity": 1,
    "price": "5,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 241,
    "item_name": "HERMES包",
    "unit": "個",
    "quantity": 1,
    "price": "15,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 242,
    "item_name": "HERMES包",
    "unit": "個",
    "quantity": 1,
    "price": "15,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 243,
    "item_name": "HERMES包",
    "unit": "個",
    "quantity": 1,
    "price": "5,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 244,
    "item_name": "HERMES包",
    "unit": "個",
    "quantity": 1,
    "price": "5,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 245,
    "item_name": "HERMES包",
    "unit": "個",
    "quantity": 1,
    "price": "10,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 246,
    "item_name": "HERMES包",
    "unit": "個",
    "quantity": 1,
    "price": "3,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 247,
    "item_name": "HERMES包",
    "unit": "個",
    "quantity": 1,
    "price": "3,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 248,
    "item_name": "LOUIS VUITTON包",
    "unit": "個",
    "quantity": 1,
    "price": "8,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 249,
    "item_name": "LOUIS VUITTON包",
    "unit": "個",
    "quantity": 1,
    "price": "10,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 250,
    "item_name": "LOUIS VUITTON包",
    "unit": "個",
    "quantity": 1,
    "price": "20,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 251,
    "item_name": "LOUIS VUITTON包",
    "unit": "個",
    "quantity": 1,
    "price": "2,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 252,
    "item_name": "LOUIS VUITTON包",
    "unit": "個",
    "quantity": 1,
    "price": "3,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 253,
    "item_name": "LOUIS VUITTON包",
    "unit": "個",
    "quantity": 1,
    "price": "2,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 254,
    "item_name": "LOUIS VUITTON包",
    "unit": "個",
    "quantity": 1,
    "price": "12,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 255,
    "item_name": "LOUIS VUITTON包",
    "unit": "個",
    "quantity": 1,
    "price": "15,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 256,
    "item_name": "LOUIS VUITTON包",
    "unit": "個",
    "quantity": 1,
    "price": "38,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 257,
    "item_name": "LOUIS VUITTON包",
    "unit": "個",
    "quantity": 1,
    "price": "35,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 258,
    "item_name": "LOUIS VUITTON包",
    "unit": "個",
    "quantity": 1,
    "price": "30,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 259,
    "item_name": "絲巾",
    "unit": "條",
    "quantity": 1,
    "price": "4,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 260,
    "item_name": "絲巾",
    "unit": "條",
    "quantity": 1,
    "price": "8,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 261,
    "item_name": "絲巾",
    "unit": "條",
    "quantity": 1,
    "price": "4,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 262,
    "item_name": "絲巾",
    "unit": "條",
    "quantity": 1,
    "price": "4,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 263,
    "item_name": "絲巾",
    "unit": "條",
    "quantity": 1,
    "price": "4,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 264,
    "item_name": "絲巾",
    "unit": "條",
    "quantity": 1,
    "price": "6,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 265,
    "item_name": "絲巾",
    "unit": "條",
    "quantity": 1,
    "price": "5,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 266,
    "item_name": "絲巾",
    "unit": "條",
    "quantity": 1,
    "price": "2,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 267,
    "item_name": "絲巾",
    "unit": "條",
    "quantity": 1,
    "price": "2,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 268,
    "item_name": "絲巾",
    "unit": "條",
    "quantity": 1,
    "price": "2,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  }
];