var auction_items = [
  {
    "item_number": 1,
    "item_name": "CHANEL 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 2,
    "item_name": "CHANEL 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 3,
    "item_name": "CHANEL 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 4,
    "item_name": "CHANEL 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 5,
    "item_name": "CHANEL 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 6,
    "item_name": "CHANEL 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 7,
    "item_name": "CHANEL 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 8,
    "item_name": "CHANEL 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 9,
    "item_name": "CHANEL 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 10,
    "item_name": "CHANEL 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 11,
    "item_name": "CHANEL 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 12,
    "item_name": "CHANEL 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 13,
    "item_name": "CHANEL 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 14,
    "item_name": "CHANEL 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 15,
    "item_name": "CHANEL 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 16,
    "item_name": "CHANEL 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 17,
    "item_name": "CHANEL 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 18,
    "item_name": "CHANEL 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 19,
    "item_name": "CHANEL 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 20,
    "item_name": "CHANEL 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 21,
    "item_name": "CHANEL 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 22,
    "item_name": "CHANEL 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 23,
    "item_name": "LV 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 24,
    "item_name": "LV 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 25,
    "item_name": "LV 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 26,
    "item_name": "LV 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 27,
    "item_name": "LV 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 28,
    "item_name": "LV 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 29,
    "item_name": "LV 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 30,
    "item_name": "LV 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 31,
    "item_name": "LV 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 32,
    "item_name": "LV 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 33,
    "item_name": "LV 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 34,
    "item_name": "HERMES 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 35,
    "item_name": "HERMES 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 36,
    "item_name": "HERMES 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 37,
    "item_name": "HERMES 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 38,
    "item_name": "HERMES 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 39,
    "item_name": "HERMES 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 40,
    "item_name": "HERMES 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 41,
    "item_name": "HERMES 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 42,
    "item_name": "HERMES 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 43,
    "item_name": "HERMES 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 44,
    "item_name": "HERMES 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 45,
    "item_name": "HERMES 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 46,
    "item_name": "HERMES 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 47,
    "item_name": "HERMES 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 48,
    "item_name": "HERMES 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 49,
    "item_name": "HERMES 皮包",
    "unit": "個",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 50,
    "item_name": "LV 絲巾",
    "unit": "條",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 51,
    "item_name": "LV 絲巾",
    "unit": "條",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 52,
    "item_name": "LV 絲巾",
    "unit": "條",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 53,
    "item_name": "LV 絲巾",
    "unit": "條",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 54,
    "item_name": "LV 絲巾",
    "unit": "條",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 55,
    "item_name": "LV 絲巾",
    "unit": "條",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 56,
    "item_name": "LV 絲巾",
    "unit": "條",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 57,
    "item_name": "LV 絲巾",
    "unit": "條",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 58,
    "item_name": "HERMES 絲巾",
    "unit": "條",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 59,
    "item_name": "HERMES 絲巾",
    "unit": "條",
    "quantity": 1,
    "price": 0,
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  }
];