var auction_items = [
  {
    "item_number": 150,
    "item_name": "LOUIS VUITTON衣服",
    "unit": "件",
    "quantity": 1,
    "price": "30,000",
    "item_description": "尺寸34",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 151,
    "item_name": "LOUIS VUITTON衣服",
    "unit": "件",
    "quantity": 1,
    "price": "20,000",
    "item_description": "尺寸不詳",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 152,
    "item_name": "LOUIS VUITTON衣服",
    "unit": "件",
    "quantity": 1,
    "price": "20,000",
    "item_description": "尺寸36",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 153,
    "item_name": "LOUIS VUITTON衣服",
    "unit": "件",
    "quantity": 1,
    "price": "8,000",
    "item_description": "尺寸34",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 154,
    "item_name": "LOUIS VUITTON衣服",
    "unit": "件",
    "quantity": 1,
    "price": "15,000",
    "item_description": "尺寸34",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 155,
    "item_name": "LOUIS VUITTON衣服",
    "unit": "件",
    "quantity": 1,
    "price": "90,000",
    "item_description": "尺寸36",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 156,
    "item_name": "LOUIS VUITTON衣服",
    "unit": "件",
    "quantity": 1,
    "price": "12,000",
    "item_description": "尺寸不詳",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 157,
    "item_name": "LOUIS VUITTON衣服",
    "unit": "件",
    "quantity": 1,
    "price": "20,000",
    "item_description": "尺寸34",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 158,
    "item_name": "LOUIS VUITTON衣服",
    "unit": "件",
    "quantity": 1,
    "price": "20,000",
    "item_description": "尺寸34",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 159,
    "item_name": "LOUIS VUITTON衣服",
    "unit": "件",
    "quantity": 1,
    "price": "16,000",
    "item_description": "尺寸34",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 160,
    "item_name": "LOUIS VUITTON衣服",
    "unit": "件",
    "quantity": 1,
    "price": "15,000",
    "item_description": "尺寸36",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 161,
    "item_name": "LOUIS VUITTON衣服",
    "unit": "件",
    "quantity": 1,
    "price": "25,000",
    "item_description": "尺寸36",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 162,
    "item_name": "LOUIS VUITTON衣服",
    "unit": "件",
    "quantity": 1,
    "price": "80,000",
    "item_description": "尺寸不詳",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 163,
    "item_name": "LOUIS VUITTON衣服",
    "unit": "件",
    "quantity": 1,
    "price": "15,000",
    "item_description": "尺寸38",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 164,
    "item_name": "LOUIS VUITTON衣服",
    "unit": "件",
    "quantity": 1,
    "price": "10,000",
    "item_description": "尺寸36",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 165,
    "item_name": "LOUIS VUITTON衣服",
    "unit": "件",
    "quantity": 1,
    "price": "15,000",
    "item_description": "尺寸36",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 166,
    "item_name": "LOUIS VUITTON衣服",
    "unit": "件",
    "quantity": 1,
    "price": "18,000",
    "item_description": "尺寸38",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 167,
    "item_name": "LOUIS VUITTON衣服",
    "unit": "件",
    "quantity": 1,
    "price": "15,000",
    "item_description": "尺寸XS",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 168,
    "item_name": "LOUIS VUITTON衣服",
    "unit": "件",
    "quantity": 1,
    "price": "15,000",
    "item_description": "尺寸34",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 169,
    "item_name": "LOUIS VUITTON衣服",
    "unit": "件",
    "quantity": 1,
    "price": "20,000",
    "item_description": "尺寸34",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 285,
    "item_name": "LOUIS VUITTON吊飾",
    "unit": "個",
    "quantity": 1,
    "price": "5,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 286,
    "item_name": "LOUIS VUITTON吊飾",
    "unit": "個",
    "quantity": 1,
    "price": "5,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 287,
    "item_name": "HERMES吊飾",
    "unit": "個",
    "quantity": 1,
    "price": "2,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 288,
    "item_name": "HERMES吊飾",
    "unit": "個",
    "quantity": 1,
    "price": "2,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 289,
    "item_name": "HERMES吊飾",
    "unit": "個",
    "quantity": 1,
    "price": "8,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 290,
    "item_name": "HERMES吊飾",
    "unit": "個",
    "quantity": 1,
    "price": "2,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 291,
    "item_name": "HERMES吊飾",
    "unit": "個",
    "quantity": 1,
    "price": "2,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 292,
    "item_name": "HERMES吊飾",
    "unit": "個",
    "quantity": 1,
    "price": "2,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 293,
    "item_name": "HERMES吊飾",
    "unit": "個",
    "quantity": 1,
    "price": "2,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 294,
    "item_name": "HERMES吊飾",
    "unit": "個",
    "quantity": 1,
    "price": "2,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 295,
    "item_name": "HERMES吊飾",
    "unit": "個",
    "quantity": 1,
    "price": "2,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  },
  {
    "item_number": 296,
    "item_name": "HERMES吊飾",
    "unit": "個",
    "quantity": 1,
    "price": "2,000",
    "item_description": "",
    "num_images": 1,
    "num_videos": 0,
    "auction_type": "變賣"
  }
];